### ISSUE TITLE
Add visualizations

### ISSUE THREAD

**Issue by jcoliver** [UAL-ODIS/data-viz-challenge#3]
A couple of nice data visualizations to show at the top of index.md might be nice. Add candidates to assets/images folder.

**Comment by kcarini** [comment]
I added a couple stock images. Nothing special. No attribution needed.

**Comment by jcoliver** [comment]
9191c13

**Comment by jcoliver** [comment]
f54d115 Move planetary movement image to FAQ and add photo to index
