### ISSUE TITLE
DS2F info still in static page

### ISSUE THREAD

**Issue by astrochun** [UAL-ODIS/data-viz-challenge#4]
Just noticed that the title for the page via the browser shows up as: "Data Visualization Challenge | **Digital Scholarship & Data Science Fellowship**"

**Comment by astrochun** [comment]
This is in the [_config.yml](https://github.com/UAL-ODIS/data-viz-challenge/edit/master/_config.yml) file

**Comment by jcoliver** [comment]
ee9863b
